### ISSUE TITLE
3 Developer Tips

### ISSUE THREAD

**Issue by Sudafly** [InfiniteATC/infiniteatc.github.io#7]
1. Handle your responsiveness through CSS, instead of checking if the users is on a mobile with JavaScript (What if I want to use a small window on PC?). You can do much cooler things and especially improve the navigation on mobile.

2. Map.html and map-ts.html are, besides the server url, exactly the same. By using `/map.html?server=expert` or `/map.html?server=training`, you can use javascript to determine which server url to be used by checking the `server` parameter. Don't write duplicate code 🙂.

3. Add a Max Width to your side navigation, it is to big on a large screen.

**Comment by Velocity23** [comment]
Thanks for the suggestions. I wrote this when I was very new to web development, so there are some things that are most certainly not using the best practices. I tend not to maintain this repo too much, especially not in the way of code quality. You're welcome to improve these yourself though, I keep an eye out for PRs still.
